name = "ICEModels"
uuid = "cc6ed2a1-c821-4d5e-a4e5-633d32adc978"
authors = ["Marko Polic mpolic2000@gmail.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
